#!/usr/bin/env bash

source .env

echo "======== GENEREATE SELF SIGNED CERTS ========";

if ! command -v mkcert &> /dev/null
then
    echo "mkcert could not be found"
    echo "You have to install it: https://github.com/FiloSottile/mkcert"
    exit
fi

mkcert -install
mkcert -key-file ./traefik/certs/key.pem -cert-file ./traefik/certs/cert.pem "$DOMAIN" "*.$DOMAIN"

echo "======== END GENEREATE SELF SIGNED CERTS ========";